### PR TITLE
Insert argument placeholders for function completions

### PR DESCRIPTION
**Pull request by raketeneis**
I tried my hand at issue #37. After completion, if the matchtype was a function, it tries to extract and insert the function arguments in the same way that was referenced in the issue. If there is a `self` argument in the beginning of the argument list, that one is not inserted.

I don't know much Emacs Lisp, so please let me know if there is a mistake or something I can improve.

### CODE REVIEW

**Comment by kngwyu** [comment]
Thanks!
I think it's great improvement, but I'm worrying about the case where racer doesn't return correct function signature.
So I'm going to test this PR after checking racer definitely returns correct function signatures.
Sorry for delay :sweat:

**Comment by Wilfred** [comment]
This worked well when I tested, and it's definitely a nice feature! Thank you :)

**Comment by sivakov512** [comment]
@raketeneis, @Wilfred, how do i disable this feature?

**Comment by shanemikel** [comment]
I would also like an option to disable the feature!

**Comment by Wilfred** [comment]
`racer-complete-insert-argument-placeholders` FWIW.

**Pull request merged**
