### PR TITLE
Packaging fixes

### PR DESCRIPTION
**Pull request by purcell**
- Remove redundant "Emacs package" description portion, and replace with a more descriptive phrase
- Add "languages" to keywords

### CODE REVIEW

**Comment by Wilfred** [comment]
Thanks.

I don't think your new package summary quite summarises what this package does. racer.el is not just completion: it supports going to definition, eldoc, and rendering help from rustdoc markdown docstrings.

I added 'official' to distinguish from the ac-racer and company-racer packages. The repos in the racer-rust GitHub organisation are official and the racer core devs contribute to them.

Other glue packages include 'A Git porcelain inside Emacs', 'Emacs integration for gist.github.com', 'Emacs interface to Google Translate.' on melpa.org. What do you think would be a better summary?

**Comment by purcell** [comment]
> I don't think your new package summary quite summarises what this package does. racer.el is not just completion: it supports going to definition, eldoc, and rendering help from rustdoc markdown docstrings.

Oh, I copied it from the docstring of the custom group, so maybe that needs fixing too.

I don't care too much, but mention of Emacs in the description of an elisp package is always redundant, and those other examples you found would ideally get fixed up too.

**Comment by Wilfred** [comment]
> Oh, I copied it from the docstring of the custom group, so maybe that needs fixing too.

Thanks, I hadn't spotted that.

This should now be fixed in ca5b2f2 -- does that look better to you?

**Comment by purcell** [comment]
Yep, great!

**Pull request closed without merging**
